#!/bin/bash
# BackupScripts version 2.0.0
#################################### License ####################################
# MIT License Copyright (c) 2023 David Krumm                                    #
# All rights reserved.                                                          #
#                                                                               #
# This source code is licensed under the MIT license found in the               #
# LICENSE file in the root directory of this source tree.                       #
#################################################################################
#                                 BackupScripts                                 #
#################################################################################
                                                                                #
unique_job_name="ChangeMeToUniqueName"                                          # Unique job name. Do not use space or underscore!!!
                                                                                #
path_to_BackupScript="/PATH/TO/BackupScript"                                    # Path to BackupScripts directory. Does not support Docker volume propagation!
                                                                                #
system_id_name="HOSTNAME"                                                       # Name to identify your System in Snapshots
                                                                                #
schedule_update_Restic_and_Rclone="monthly: 1"                                  # Schedule for the execution of the respective sub-process:
                                                                                # "never", "always", "weekly: Mon Tue Wed Thu Fri Sat Sun", "monthly: 1 7 14 21 28"
                                                                                # Executed only once per day if the weekly or monthly pattern is used.
                                                                                #
notify_after_completion="true"                                                  # (true/false) The notification system must be set up. See documentation.
                                                                                #
############################## Backup (Restic) ##################################
                                                                                #
schedule_backup="always"                                                        #
                                                                                #
path_to_the_directory_to_be_backed_up="/PATH/TO/DATA:ro"                        # Source directory to be backed up. Support for Docker volume propagation! E.G. "/PATH/TO/DATA:rw,slave" ro=read-only, rw=read-write 
                                                                                #
path_to_restic_repository="/PATH/TO/REPO:rw,slave"                              # Path to the backup repository. Support for Docker volume propagation! E.G. "/PATH/TO/REPO:rw,slave" ro=read-only, rw=read-write 
                                                                                #
name_restic_password_file="restic-repo.password"                                # File in Config/RepositoryPassword. Insert yor repository password first.
                                                                                #
restig_backup_tags="--tag FirstTag --tag SecondTag"                             # Tags to be applied to the backup snapshots
                                                                                #
name_restic_filter_file="DefaultResticFilter.txt"                               # Filter file to exclude specific files or directories from the backup
                                                                                #
restic_options=""                                                               # Additional options specific to Restic. Check with the documentation.
                                                                                #
name_docker_config_file="DockerExampleConfig.txt"                               #
                                                                                #
reverse_docker_start_sequence="false"                                           #
                                                                                #
############################## Forget (Restic) ##################################
                                                                                #
schedule_forget="weekly: Mon Wed Sat"                                           #
                                                                                #
keep_hourly_for="48h"                                                           # Number of hours to keep hourly snapshots
keep_daily_for="7d"                                                             # Number of days to keep daily snapshots
keep_weekly_for="3m"                                                            # Number of weeks to keep weekly snapshots
keep_monthly_for="1y"                                                           # Number of months to keep monthly snapshots
keep_yearly_for="5y"                                                            # Number of years to keep yearly snapshots
                                                                                #
############################## Prune (Restic) ##################################
                                                                                #
schedule_prune="monthly: 1 15"                                                  #
                                                                                #
############################## Remote Copy (Rclone) #############################
                                                                                #
schedule_rclone="weekly: The Sun"                                               #
                                                                                #
rclone_remote_path="RemoteName:/PATH/ON/REMOTE"                                 # Destination remote for Rclone. Does not support Docker volume propagation!
                                                                                #
name_rclone_filter_file="DefaultRcloneFilter.txt"                               # Filter file to exclude specific files or directories from the backup to remote
                                                                                #
rclone_options="--log-level INFO"                                               # Additional options specific to Rclone. Check with the documentation.
                                                                                # Example: --dry-run --max-delete=50 --bwlimit 10M --log-level DEBUG
                                                                                #
#################################################################################



























#################################################################################
#                        Don't change the following lines                       #
#################################################################################

if [ ! -f "$path_to_BackupScripts/Executor/MainExec" ]; then
        echo "!!!!!!!!!!!!!!!!!!!!! ERROR !!!!!!!!!!!!!!!!!!!!!!"
        echo ""
        echo "Project "BackupsScripts" was set up incorrectly."
        echo "Please check the setup by following the instructions."
        echo "-> File '$path_to_BackupScripts/Executor/MainExec' not found."
        echo ""
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        exit 1
fi
source $path_to_BackupScripts/Executor/MainExec

#################################################################################