#!/bin/bash
# BackupScripts version 1.0.3
#################################### License ################################
# MIT License Copyright (c) 2023 David Krumm                                #
# All rights reserved.                                                      #
#                                                                           #
# This source code is licensed under the MIT license found in the           #
# LICENSE file in the root directory of this source tree.                   #
################################# Parameters ################################
channel="$1"                                                                # Channel of the message output
args="$2"                                                                   # Specific argument
message="$3"                                                                # Message to send
################################# Variables ################################
timestamp="$(date +%F_%T)"                                                  # Log timestamp
# Path to logfile
log_file="$HOME_PATH/LogFiles/${JOB_NAME}_logging.log"                      # Path to log file
mkdir -p "$(dirname "$log_file")"
#############################################################################


#############################################################################
#                  Adjust the code below to suit your needs                 # 
#############################################################################
################################# Interfaces ################################

to_terminal() {
    # Send message to log and log file
    local msg="$1"
    echo "$msg"
}

to_logfile() {
    # Send message to log and log file
    local msg="$1"
    echo "$msg" >> "$log_file"
}

to_unraid_notification() {
    # Send to Unraid notification system
    local severity="$1"
    local msg="$2"
    "/usr/local/emhttp/webGui/scripts/notify" -i "$severity" -e "BackupScripts" -s "$JOB_NAME" -d "$msg"
}

to_mail() {
    local msg="$1"
    #
    # Implement your code
    #
}

implement_your_nofification_system() {
    local msg="$1"
    #
    # Implement your code
    #
}

################################# Send ######################################

if [[ "$channel" == -1 ]]; then      # Log without timestamp
    to_terminal "$message"
    to_logfile "$message"
    
elif [[ "$channel" == 0 ]]; then
    to_terminal "$timestamp - ERROR: No level set for Notification"
    to_logfile "$timestamp - ERROR: No level set for Notification"
    exit 1

elif [[ "$channel" == 1 ]]; then     # Message to logfile
    to_terminal "$timestamp - $message"
    to_logfile "$timestamp - $message"

elif [[ "$channel" == 2 ]]; then     # Message to notification system
    # to_unraid_notification "$args" "$message"                             # Uncomment if you use Unraid as system
    # to_mail                                                               # Implement your code to use
    # implement_your_nofification_system                                    # Implement your code to use
    true
fi                                                     