#!/bin/bash
# BackupScripts version 1.0.3
#################################### License ################################
# MIT License Copyright (c) 2023 David Krumm                                #
# All rights reserved.                                                      #
#                                                                           #
# This source code is licensed under the MIT license found in the           #
# LICENSE file in the root directory of this source tree.                   #
################################# Parameters ################################
source="$1"                                                                 # Directory to be backed up
destination="$2"                                                            # Destination directory of the data backup
filter_options="$3"                                                         # Settings for filtering files
logging_options="$4"                                                        # Settings for the logging of rclone
options="$5"                                                                # Additional rclone options
######################### Docker Volume Propagation #########################

if [[ $source == *":"* ]]; then
    source_prop=":$(echo "$source" | cut -d ":" -f 2)"
    source=$(echo "$source" | cut -d ":" -f 1)
else
    source_prop=""
fi

################################# Backup ####################################

cmd="docker run --rm --name $JOB_NAME-RcloneBackup \
    --volume $HOME_PATH/Config/RcloneConfig:/config/rclone \
    --volume $HOME_PATH/LogFiles:/LogFiles \
    --volume $HOME_PATH/Config/FilterConfig/RcloneFilter:/FilterFiles \
    --volume $source:/source$source_prop \
    --user $(id -u):$(id -g) \
    rclone/rclone sync /source $destination \
    $filter_options $logging_options $options"

# progress message
$NOTIFIER --channel "file"
$NOTIFIER --channel "file" --message "Backup in progress ... "
$NOTIFIER --channel "file"
$NOTIFIER --channel "file" --message "$cmd"

eval $cmd
exit_code=$?

################################# Evaluation ################################

if [[ "$exit_code" == 0 ]]; then
    $NOTIFIER --channel "file"
    $NOTIFIER --channel "file" --message "Completed 'backup' job to '$destination' successfully"
    exit 0
else
    $NOTIFIER --channel "file" --timestamps "false"
    $NOTIFIER --channel "system" --args "warning" --message "ERROR $JOB_NAME: Rclone to '$destination' failed with exit_code=$exit_code"
    $NOTIFIER --channel "file" --timestamps "false"
    exit 1
fi