#!/bin/bash
# BackupScripts version 1.0.3
#################################### License ################################
# MIT License Copyright (c) 2023 David Krumm                                #
# All rights reserved.                                                      #
#                                                                           #
# This source code is licensed under the MIT license found in the           #
# LICENSE file in the root directory of this source tree.                   #
################################# Parameters ################################
repo="$1"                                                                   # Destination directory of the data backup
password_file="$2"                                                          # Password file of restic repo
keep_rules="$3"                                                             # Rules for keeping snapshots
######################### Docker Volume Propagation #########################

if [[ $repo == *":"* ]]; then
    repo_prop=":$(echo "$repo" | cut -d ":" -f 2)"
    repo=$(echo "$repo" | cut -d ":" -f 1)
else
    repo_prop=""
fi

################################### Forget ##################################

cmd="docker run --rm --name $JOB_NAME-ResticForget \
    --volume $HOME_PATH:/home \
    --volume $repo:/repo$repo_prop \
    --user $(id -u):$(id -g) \
    restic/restic \
    --password-file=/home/Config/ResticConfig/$password_file \
    -r /repo forget $keep_rules"

# progress message
$NOTIFIER --channel "file"
$NOTIFIER --channel "file" --message "Forget in progress ... "
$NOTIFIER --channel "file" --message "Keep-Rules: '$keep_rules'"
$NOTIFIER --channel "file"
$NOTIFIER --channel "file" --message "$cmd"

output=$(eval $cmd)
$NOTIFIER --channel "file" --message "$output" --timestamps "false"
exit_code=$?

################################# Evaluation ################################

if [[ "$exit_code" == 0 ]]; then
    $NOTIFIER --channel "file"
    $NOTIFIER --channel "file" --message "Completed 'forget' job of '$repo' successfully"
    exit 0
else
    $NOTIFIER --channel "file" --timestamps "false"
    $NOTIFIER --channel "system" --args "warning" --message "ERROR $JOB_NAME:  Forget of '$repo' failed with exit_code=$exit_code"
    $NOTIFIER --channel "file" --timestamps "false"
    exit 1
fi