#!/bin/bash
# BackupScripts version 1.0.3
#################################### License ################################
# MIT License Copyright (c) 2023 David Krumm                                #
# All rights reserved.                                                      #
#                                                                           #
# This source code is licensed under the MIT license found in the           #
# LICENSE file in the root directory of this source tree.                   #
################################# Parameters ################################
hostname="$1"                                                               # Set host name for detection of snapshots in the repo
source="$2"                                                                 # Directory to be backed up
repo="$3"                                                                   # Destination directory of the data backup
password_file="$4"                                                          # Password file of restic repo
filter_file="$5"                                                            # Path to filter file
tags="$6"                                                                   # Tags for marking snapshots
options="$7"                                                                # Additional Restic options
################################ Docker Handling ###########################
handle_docker="$8"                                                          # "true" or "false" to activate or deactivate Docker handling
stop_start_remaining_container="$9"                                         # "true" to stop and start all "running" containers before backup, "false" to skip
reverse_on_start="${10}"                                                    # "true" to reverse the order of the container_list at start-up
shift 10                                                                    #
container_list=("$@")                                                       # List and sequence of containers to be stopped
######################### Docker Volume Propagation #########################

if [[ $source == *":"* ]]; then
    source_prop=":$(echo "$source" | cut -d ":" -f 2)"
    source=$(echo "$source" | cut -d ":" -f 1)
else
    source_prop=""
fi

if [[ $repo == *":"* ]]; then
    repo_prop=":$(echo "$repo" | cut -d ":" -f 2)"
    repo=$(echo "$repo" | cut -d ":" -f 1)
else
    repo_prop=""
fi

################################## Funktions ################################

call_notifier() {
    local channel="$1"
    local args="$2"
    local mes="$3"
    "$HOME_PATH/Executor/Notifier" "$channel" "$args" "$mes"
}

reverse_array() {
    local original_array=("$@")
    local reversed_array=()

    for ((i=${#original_array[@]}-1; i>=0; i--)); do
        reversed_array+=("${original_array[i]}")
    done

    echo "${reversed_array[@]}"
}

convert_array_to_print() {
  local array=("$@")
  local result=""
  
  for element in "${array[@]}"; do
    result+=" $element"
  done
  result="${result# }"

  echo "$result"
}

start_stop_containers() {

    local command="$1"
    shift
    local containers=("$@")
    call_notifier "1" "" ""
    call_notifier "1" "" "Execute '${command}' for docker containers: '$(convert_array_to_print "${containers[@]}")'"

    for con in "${containers[@]}"; do
        call_notifier "1" "" "Execute '$command' for '$con' ..."
        docker "$command" "$con"

        # Wait for container to stop/start within a timeout period
        local timeout=30
        local interval=5
        local elapsed=0

        while true; do
            container_status=$(docker inspect -f '{{.State.Status}}' "$con")
            if [[ "$command" == "start" ]]; then
                status="running"
            else
                status="exited"
            fi
            if [[ "$container_status" == "$status" ]]; then
                call_notifier "1" "" "$con has successfully changed its status"
                break
            fi
            if (( elapsed >= timeout )); then
                call_notifier "-1" "" ""
                call_notifier "1" "" "ERROR $JOB_NAME: Timeout container '$con' failed to '$command'"
                call_notifier "-1" "" ""
                exit 1
            fi
            sleep "$interval"
            elapsed=$((elapsed + interval))
        done
        sleep 5
    done
}

################################### Backup ##################################

call_notifier "1" "" ""
call_notifier "1" "" "Starting 'backup' job of '$source'"

################################### Stop Docker Container

# Skip if handle_docker is set to false
if [[ "$handle_docker" == "true" ]]; then

    # Stop containers in the container_list
    start_stop_containers "stop" "${container_list[@]}"
    #generate list of remaining running container and stop them
    if [ "$stop_start_remaining_container" = "true" ]; then
        docker_result=$(docker container ls -q)									
        IFS=$'\n' read -rd '' -a containers <<< "$docker_result"
        start_stop_containers "stop" "${containers[@]}"
    fi

else
    call_notifier "1" "" ""
    call_notifier "1" "" "Container handling deactivated"
fi

################################### Restic Backup

cmd="docker run --rm --name $JOB_NAME-ResticBackup \
    --hostname $hostname \
    --volume $HOME_PATH:/home \
    --volume $source:/source$source_prop \
    --volume $repo:/repo$repo_prop \
    --user $(id -u):$(id -g) \
    restic/restic \
    --password-file=/home/Config/ResticConfig/$password_file \
    -r /repo backup /source $tags \
    --exclude-file=/home/FilterFiles/ResticFilter/$filter_file \
     $options"

# progress message
call_notifier "1" "" ""
call_notifier "1" "" "Backup in progress ... "
call_notifier "1" "" ""
call_notifier "1" "" "$cmd"

output=$(eval $cmd)
call_notifier "-1" "" "$output"
exit_code=$?

################################### Start Docker

# Skip if handle_docker is set to false
if [[ "$handle_docker" == "true" ]]; then

    #start container of generated list
    if [[ "$stop_start_remaining_container" == "true" ]]; then
        start_stop_containers "start" "${containers[@]}"
    fi
    #start container of list "container_list"
    if [[ "$reverse_on_start" == "true" ]]; then
        container_list=($(reverse_array "${container_list[@]}"))
    fi
    start_stop_containers "start" "${container_list[@]}"
fi

################################# Evaluation ################################

if [[ "$exit_code" == 0 ]]; then
    call_notifier "1" "" ""
    call_notifier "1" "" "Completed 'backup' job of '$source' successfully"
    exit 0
else
    call_notifier "-1" "" ""
    call_notifier "1" "" "ERROR $JOB_NAME: Backup of '$source' failed with exit_code=$exit_code"
    call_notifier "-1" "" ""
    exit 1
fi