#!/bin/bash
# BackupScript version 2.0.0
#################################### License ################################
# MIT License Copyright (c) 2023 David Krumm                                #
# All rights reserved.                                                      #
#                                                                           #
# This source code is licensed under the MIT license found in the           #
# LICENSE file in the root directory of this source tree.                   #
#############################################################################

################################# Parameters ################################

keep_rules="$1"                                                             # Rules for keeping snapshots

######################### Docker Volume Propagation #########################

repo="$REPOSITORY"

if [[ $repo == *":"* ]]; then
    repo_prop=":$(echo "$repo" | cut -d ":" -f 2)"
    repo=$(echo "$repo" | cut -d ":" -f 1)
else
    repo_prop=""
fi

################################### Restic ##################################

$NOTIFIER
$NOTIFIER --message "Starting 'Forget' job"
$NOTIFIER --message "Repository '$repo'"

################################### Forget

cmd="docker run --rm --name $JOB_NAME-ResticForget \
    --volume $(dirname "$RESTIC_PW"):/password \
    --volume $repo:/repo$repo_prop \
    --user $(id -u):$(id -g) \
    restic/restic \
    --password-file=/password/$(basename "$RESTIC_PW") \
    -r /repo forget $keep_rules"

# progress message
$NOTIFIER
$NOTIFIER --message "Forget in progress ... "
$NOTIFIER --message "Keep-Rules: '$keep_rules'"
$NOTIFIER
$NOTIFIER --message "$cmd" --timestamps "false"

output=$(eval "$cmd" 2>&1)
exit_code=$?
output=${output//%/%%}
$NOTIFIER --message "$output" --timestamps "false"

################################# Evaluation ################################

if [[ "$exit_code" == 0 ]]; then
    $NOTIFIER
    $NOTIFIER --message "Completed 'Forget' job of '$repo' successfully"
    exit 0
else
    $NOTIFIER --timestamps "false"
    $NOTIFIER --channel "important" --type "warning" --message "ERROR $JOB_NAME: Forget of '$repo' failed with exit_code=$exit_code"
    $NOTIFIER --timestamps "false"
    exit 1
fi