#!/bin/bash
# BackupScripts version 2.0.0
#################################### License ################################
# MIT License Copyright (c) 2023 David Krumm                                #
# All rights reserved.                                                      #
#                                                                           #
# This source code is licensed under the MIT license found in the           #
# LICENSE file in the root directory of this source tree.                   #
################################# Parameters ################################
hostname="$1"                                                               # Set host name for detection of snapshots in the repo
tags="$2"                                                                   # Tags for marking snapshots
options="$3"                                                                # Additional Restic options
######################### Docker Volume Propagation #########################

$source="$SOURCE"
$repo="$REPOSITORY"

if [[ $source == *":"* ]]; then
    source_prop=":$(echo "$source" | cut -d ":" -f 2)"
    source=$(echo "$source" | cut -d ":" -f 1)
else
    source_prop=""
fi

if [[ $repo == *":"* ]]; then
    repo_prop=":$(echo "$repo" | cut -d ":" -f 2)"
    repo=$(echo "$repo" | cut -d ":" -f 1)
else
    repo_prop=""
fi

################################### Restic ##################################

$NOTIFIER --channel "file"
$NOTIFIER --channel "file" --message "Starting 'Backup' job"
$NOTIFIER --channel "file" --message "Source '$source'"
$NOTIFIER --channel "file" --message "Repository '$repo'"
$NOTIFIER --channel "file" --message "Use filter '$(basename "$RESTIC_FILTER")'"

################################### Backup

cmd="docker run --rm --name $JOB_NAME-ResticBackup \
    --hostname $hostname \
    --volume $(dirname "$RESTIC_PW"):/password \
    --volume $(dirname "$RESTIC_FILTER"):/filterfile \
    --volume $source:/source$source_prop \
    --volume $repo:/repo$repo_prop \
    --user $(id -u):$(id -g) \
    restic/restic \
    --password-file=/password/$(basename "$RESTIC_PW") \
    -r /repo backup /source $tags \
    --exclude-file=/filterfile/$(basename "$RESTIC_FILTER") \
     $options"

# progress message
$NOTIFIER --channel "file"
$NOTIFIER --channel "file" --message "Backup in progress ... "
$NOTIFIER --channel "file"
$NOTIFIER --channel "file" --message "$cmd"

output=$(eval $cmd)
$NOTIFIER --channel "file" --message "$output" --timestamps "false"
exit_code=$?

################################# Evaluation ################################

if [[ "$exit_code" == 0 ]]; then
    $NOTIFIER --channel "file"
    $NOTIFIER --channel "file" --message "Completed 'backup' job of '$source' successfully"
    exit 0
else
    $NOTIFIER --channel "file" --timestamps "false"
    $NOTIFIER --channel "system" --args "warning" --message "ERROR $JOB_NAME: Backup of '$source' failed with exit_code=$exit_code"
    $NOTIFIER --channel "file" --timestamps "false"
    exit 1
fi