#!/bin/bash
# BackupScripts version 2.0.0
#################################### License ################################
# MIT License Copyright (c) 2023 David Krumm                                #
# All rights reserved.                                                      #
#                                                                           #
# This source code is licensed under the MIT license found in the           #
# LICENSE file in the root directory of this source tree.                   #
#############################################################################

######################### Docker Volume Propagation #########################

repo="$REPOSITORY"

if [[ $repo == *":"* ]]; then
    repo_prop=":$(echo "$repo" | cut -d ":" -f 2)"
    repo=$(echo "$repo" | cut -d ":" -f 1)
else
    repo_prop=""
fi

################################### Restic ##################################

$NOTIFIER --channel "file"
$NOTIFIER --channel "file" --message "Starting 'Prune' job"
$NOTIFIER --channel "file" --message "Repository '$repo'"

################################### Prune 

cmd="docker run --rm --name $JOB_NAME-ResticPrune \
    --volume $(dirname "$RESTIC_PW"):/password \
    --volume $repo:/repo$repo_prop \
    --user $(id -u):$(id -g) \
    restic/restic \
    --password-file=/password/$(basename "$RESTIC_PW") \
    -r /repo prune"

# progress message
$NOTIFIER --channel "file"
$NOTIFIER --channel "file" --message "Prune in progress ... "
$NOTIFIER --channel "file"
$NOTIFIER --channel "file" --message "$cmd" --timestamps "false"

output=$(eval $cmd)
$NOTIFIER --channel "file" --message "$output" --timestamps "false"
exit_code=$?

################################# Evaluation ################################

if [[ "$exit_code" == 0 ]]; then
    $NOTIFIER --channel "file"
    $NOTIFIER --channel "file" --message "Completed 'prune' job of '$repo' successfully"
    exit 0
else
    $NOTIFIER --channel "file" --timestamps "false"
    $NOTIFIER --channel "system" --args "warning" --message "ERROR $JOB_NAME: Prune of '$repo' failed with exit_code=$exit_code"
    $NOTIFIER --channel "file" --timestamps "false"
    exit 1
fi